# Generated by Django 4.1.7 on 2023-04-13 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapplications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('pilot_in_command', models.BooleanField()),
                ('current_aircraft_type', models.CharField(max_length=20)),
                ('faa_part_type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='pic_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='sic_time',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='RatingsHeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.BooleanField()),
                ('multi_engine', models.BooleanField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_class', models.IntegerField()),
                ('medical_date', models.DateField()),
                ('examiner_name', models.CharField(max_length=50)),
                ('examiner_phone', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificatesHeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.BooleanField()),
                ('sport', models.BooleanField()),
                ('recreational', models.BooleanField()),
                ('private_pilot', models.BooleanField()),
                ('csel', models.BooleanField()),
                ('cmel', models.BooleanField()),
                ('atp', models.BooleanField()),
                ('cfi', models.BooleanField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
