# Generated by Django 4.1.7 on 2023-04-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapplications', '0002_accountdetail_flight_pic_time_flight_sic_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medical',
            options={'get_latest_by': 'medical_date'},
        ),
    ]
