# Generated by Django 4.1.7 on 2023-04-16 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapplications', '0003_alter_medical_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatesheld',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ratingsheld',
            name='id',
        ),
        migrations.AlterField(
            model_name='certificatesheld',
            name='pilot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratingsheld',
            name='pilot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
